ortac.opam
src/core/failure.ml
src/core/failure.mli
src/core/ortac.ml
src/core/translation.ml
src/core/translation.mli

This uses the original text written in the specification to report errors.

Better reporting for terms

---

src/monolith/generators.ml
src/monolith/ortac_monolith.ml
src/monolith/printers.ml
src/monolith/runtime/ortac_runtime_monolith.ml
src/monolith/runtime/ortac_runtime_monolith.mli
src/monolith/spec.ml

In this PR, I add support for abstract types in the frontend for `monolith`.
- In presence of an abstract type, it will be declared to `monolith` in the generated file.
- Alpha types are constrained to `int`. This seems a reasonable choice in most of the cases.
- A better array generator is given.

Abstract types for monolith frontend

---

src/core/drv.ml
src/core/translate.ml
src/core/translated.ml
src/core/types.ml
src/core/types.mli
test/suite/dune
test/suite/test.ml
test/suite/translation.ml
test/suite/translation/dependant.ml
test/suite/translation/dependant.mli
test/suite/translation/dune
test/suite/translation/immutable.mli
test/suite/translation/mutable.mli
test/suite/translation/pure.mli
test/suite/translation/unknown.mli

Traverse a type definition to compute whether it is an OCaml mutable type. 
This allows to have information even in the absence of specifications.
I also add some tests.

Compute mutability of type before processing specifications

---

bin/dune

These dependencies dates from the first separated cli but are no longer needed.

remove ppxlib and ppxlib.ast dependencies for cli

---

ortac.opam

`Alcotest.failf` was added in [0.8.1](https://github.com/mirage/alcotest/blob/main/CHANGES.md#081-2017-08-03)

Fixes lower bound for alcotest

---

src/core/builder.ml
src/core/context.ml
src/core/dune
src/core/string.pre413.ml
src/runtime/ortac_runtime.ml
src/runtime/ortac_runtime_intf.ml
test/generated/default/wrapper.expected.ml
test/generated/monolith/wrapper.expected.ml

This is really a one-commit PR, but it was based on #72.
Instead of hard-coding an association table that maps Gospel Stdlib values to their equivalent OCaml code, expect the target runtime to provide its own implementation in the Ortac_runtime.Gospelstdlib module, following exactly the same structure as the Gospel Stdlib. Consequently, Ortac_runtime_intf.Gospelstdlib could be generated (using fold_namespace for instance...). It is still handwritten, because the implementation is real only partial for now.
That restructuring makes it clearer which parts of the runtime is exposed to support the specification translations and which parts should really only be used by the generator (`Z.forall`, `Z.exists`). On the other hand, the generator does call the functions that are provided by the …

Map the full Gospelstdlib to the Ortac_runtime.Gospelstdlib module

---

dune

Configure in details the default and runtest aliases

Configure `dune build` to skip the tests by default

---

plugins/monolith/generators.ml
plugins/monolith/printers.ml
plugins/monolith/spec.ml
test/generated/default/dune
test/generated/dune.common
test/generated/monolith/dune
test/generated/monolith/wrapper.expected.ml

The plugin was broken during the last gospel update.
This PR does two things:
1. Make the monolith plugin handle private types as abstract
2. Refactor dune files for the tests, mainly lib.mli is not the correct interface for the wrapper.ml generated by ortac-monolith

Fix monolith plugin

---

src/core/ocaml_of_gospel.ml
src/core/warnings.ml

This PR proposes to make `Ortac_core.Warnings.kind` an extensible type. The rational is that plugins can come with their own warnings. This allows them to reuse the `Ortac_core` warning mechanism by extending the `kind` type, the `level` and the `pp_kind` functions.

Make Warnings.kind an extensible type

---

src/core/context.ml
src/runtime/ortac_runtime.ml
src/runtime/ortac_runtime_intf.ml

Extend the supported subset of the gospel standard library with a subset of the List module (fix #85).
This should be enough in order to write some meaningful tests for the `qcheck-stm` plugin, as most of the time, `stm` models are lists.
There is no need to add too much of the List module, as the gospel standard library is expected to change in a near future.

Add a subset of `Gospelstdlib.List` to the supported subset

---

plugins/qcheck-stm/test/dune

It would be nice to be able to easily trigger the generated tests, rather than stopping at generating them.
This PR proposes a different alias, `launchtests` for that. It currently only defines the behaviour for the QCheck-STM plugin, in part because the Monolith plugin comes with two tests runners (both might be attached, at least when `afl-fuzz` is available) that intentionally do not terminate (which makes it less clearly useful in an alias).

Add a `launchtests` alias to run the _generated_ QCheck-STM tests

---

dune
plugins/dune
plugins/monolith/dune
plugins/qcheck-stm/dune

This was another [PR](n-osborne/ortac#19), shown as merged, but it vanished before getting to the actual `main`.

Detach plugin tests from the `default` build target

---

plugins/qcheck-stm/src/ir.ml
plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/errors.expected
plugins/qcheck-stm/test/stm_tests.expected.ml
src/core/ocaml_of_gospel.ml
src/core/ocaml_of_gospel.mli
src/default/ir_of_gospel.ml

`qcheck-stm` wrap returned values of function that may raises an exception in a result type, so that it can tell something in the `postcond` function.
In order to support exceptional postconditions and checks clauses (gospel ones), we have to:
1. amend the `run` function that we generate:
- a function that may raise an exception and which returned type is `'a`  will be encoded as returning an `('a, exn) result`
- a function that may raise an exception will be called wrapped in the `protect` combinator provided by `qcheck-stm`
2. amend the `postcond` function that we generate so that it will make the appropriate verifications.
As gospel has a different semantic for the `raises` clauses (exceptional posticonditions) and the `checks` clauses, we generate an expression of the form:
```
if all …
```

Support exceptional postconditions and checks clauses

---

src/core/context.ml
src/runtime/ortac_runtime.ml
src/runtime/ortac_runtime_intf.ml

This PR should be reviewed commit by commit, each commit message explains (in quite some details) what this PR brings.
TLDR:
- a lot more specifications should be translatable now!
- it provides an ascii encoding for the mixfix operators in order to be OCaml-syntax compatible,
- it completes the Ortac runtime with the functions from the OCaml Stdlib (leaving out functions or modules that are not so obvious, such as `Bag` and `Set`),
- it completes the Ortac-runtime interface with the whole Gospel Stdlib, with `alert` attributes on functions that are implemented, so that it pushes warning from the code generator stage to the compiling-the-generated-code stage, ie when the Ortac runtime is actually involved.
On that last aspect, it might make more sense, instead of assuming that the whole …

Rewrite the Ortac-runtime implementation of the Gospel Stdlib

---

src/runtime/ortac_runtime.ml
src/runtime/ortac_runtime_intf.ml

Implement the `Bag` and `Set` modules of the Gospel Stdlib.
Define `BagSet` to factorise the implementations of `Bag` and `Set`.
`bag` and `set` are implemented as decreasing sorted lists where each element appears at most once, using the polymorphic comparison.
For `bag`s, the list contains pairs, where `snd x` is the number of occurrences of `fst x`, with `snd x > 0`.
Rationale: obviously, the time complexity of these implementations is not ideal, but:
- it is a purely functional implementation (so it can be used with QCheck-STM),
- it is compatible with the polymorphic equality: Ortac uses OCaml's `(=)` to implement Gospel's `(=)`, this ensures that `set`s and `bag`s can be tested for equality in the generated code,
- they are sorted in decreasing order so that the resulting order …

Implement the full Gospel Stdlib

---

plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/hashtbl_errors.expected
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml

This PR fixes #101 
A filtering of higher order values is added in the `ir_of_gospel` step as the pretty printer library does not support functional values. As `cmd`s correponding to higher order values are not generated in `arb_cmd` anywat, an other strategy would have been to let the pretty printer fail in these cases which it will never encounter. But now the user has a bit more information.

Cmd pretty printer

---

src/core/ocaml_of_gospel.ml

Before
```
forall x. 0 < x /\ x < 10 -> P
```
was accepted, but not
```
forall x. 0 < x && x < 10 -> P
```
This PR proposes to accept it, as I don't see any reason why it shouldn't.

Add assymetric conjunction to possible quantification

---

ortac-runtime.opam
test/runtime/dune
test/runtime/stdlibset.ml

Test the `Gospelstdlib.Set` module with `int` values by comparing it with the OCaml `Stdlib.Set` implementation
Use the `timeout` command to run 30 seconds of tests (but still build `stdlibset.exe` in any case)
As `Bag` shares most of its code with `Set`, this PR gives some pretty good confidence over the implementation.

Add a monolith test for the `Gospelstdlib.Set` module

---

plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml

qcheck-stm: Avoid `{ state with ... }` syntax when all models are updated

---

plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli

Filtering in a radical way to avoid generating broken code such as
translation of specifications using unbound ghost arguments.
Co-authored-by: @shym

Filter out functions with ghost values

---

plugins/qcheck-stm/src/config.ml
src/core/warnings.ml

Add basic support for Gospel errors in Ortac Core and use that to report properly Gospel errors in the qcheck-stm plugin

Route Gospel errors as other errors in qcheck-stm plugin

---

plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/test/hashtbl_errors.expected

Tested locally, automatic tests are comming in seperated PR testing all warnings.
Fix #123

Seperate monadic checks and assertion.

---

dune-project

Reformat `dune-project` even if `dune fmt` does not do it automatically, for consistency

Reformat `dune-project`

---

bin/cli.ml
plugins/monolith/src/dune
plugins/monolith/test/generated/dune
plugins/qcheck-stm/src/dune
plugins/qcheck-stm/test/dune
plugins/wrapper/src/dune
plugins/wrapper/test/generated/dune
plugins/wrapper/test/suite/dune.common

The current work-around breaks `opam install --with-test ...` as the tests of each plugin depends on all plugins, from other packages (and but we really don't want to add an OPAM dependency on all plugins). So this PR introduces another work-around, inspired by a comment in ocaml/dune#8283: if `$ORTAC_ONLY_PLUGIN` is set up, load only the plugin of that name. This is using an environment variable rather than a command-line argument because the plugins provide the command-line parsers...

Use a better work-around for the `dune-site` dependency problem for tests

---

.github/workflows/build.yml
bin/cli.ml
plugins/monolith/src/dune
plugins/monolith/test/generated/dune
plugins/qcheck-stm/src/dune
plugins/qcheck-stm/test/dune
plugins/wrapper/src/dune
plugins/wrapper/test/generated/dune
plugins/wrapper/test/suite/dune.common

This PR adds a new CI workflow that runs all the tests in an action.
The goals are to:
- test the installation of the OPAM package (not tested by OCaml-CI) to make sure we are ready before we release,
- test the noisy tests (that are not attached to `@runtest` because they are noisy),
- provide a fallback for when OCaml-CI is overwhelmed.
This is based on #127 to have the OPAM installation working.

Add a Github Action CI workflow to run all the tests

---

src/core/ocaml_of_gospel.ml

Translate Gospel type `integer` as `Ortac_runtime.integer` (so that the runtime can choose its implementation) rather than hard-coding it as `int`. Choosing `int` makes it inconsistent with all the implementations of the Gospel Stdlib in `Ortac_runtime` (where `Z.t` is used)

Translate Gospel `integer` as `Ortac_runtime.integer`

---

plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/test_errors.t

This PR add some test for the warning system of the `ortac-qcheck-stm` plugin.
- A diff test to test the warnings of level warning (each function of the module raising a different warning).
- A cram test to test the warnings of level error

testing warnings

---

plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/record.ml
plugins/qcheck-stm/test/record.mli
plugins/qcheck-stm/test/record_errors.expected
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref.ml
plugins/qcheck-stm/test/ref.mli
plugins/qcheck-stm/test/ref_errors.expected
plugins/qcheck-stm/test/ref_stm_tests.expected.ml

In the QCheck-STM framework, the code generated to test whether clauses hold will be run with only the model state in scope, not the actual non-model values. `subst_term` will ensure that the substitution is indeed used in such a case instead of generating non-compiling code. This adds a new error case to report those impossible substitutions.
Add two simple tests (`ref` and record) that didn't compile before this PR.
This is based on #134 because it is using a `integer` in a model.

Restrict `subst_term` to `x.f` where `f` is a model field

---

ortac-core.opam
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected
plugins/wrapper/src/ir_of_gospel.ml
src/core/ocaml_of_gospel.ml

This PR:
- updates the pinned gospel version, to bring its latest compatibility-breaking changes,
- bring support for patterns as arguments of anonymous functions, following ocaml-gospel/gospel#309.
As soon as gospel 0.2 is released, the pin should be dropped and converted into a regular version dependency, but this will help transition smoothly until then.

Bring Ortac up-to-date with the current development version of Gospel

---

bin/registration.ml
bin/registration.mli
plugins/monolith/src/ortac_monolith.ml
plugins/monolith/src/ortac_monolith.mli
plugins/qcheck-stm/src/ortac_qcheck_stm.ml
plugins/qcheck-stm/test/dune
plugins/wrapper/src/generate.ml
plugins/wrapper/src/generate.mli
plugins/wrapper/src/ortac_wrapper.ml

- Update the pinned gospel version
- Support patterns as arguments of anonymous functions
- Add output option to qcheck-stm plugin cli
- Use the new output option in qcheck-stm tests

Add an output option to qcheck-stm plugin cli

---

plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref_stm_tests.expected.ml

Use a `[@@@ocaml.warning]` attribute in order to lighten the dune files
expected from the user.
Close #138

Disable warnings in generated code

---

plugins/monolith/src/warnings.ml
plugins/monolith/test/generated/errors.expected
plugins/qcheck-stm/src/ir.ml
plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected
plugins/qcheck-stm/test/hashtbl_errors.expected
plugins/qcheck-stm/test/record_errors.expected
plugins/qcheck-stm/test/ref_errors.expected
plugins/qcheck-stm/test/test_errors.t
plugins/wrapper/src/report.ml
plugins/wrapper/test/generated/errors.expected
src/core/warnings.ml

These two parts could be seen as fairly independent but I think that using `pp_fix` has a deep impact on what we would like to see in the message: as `pp_loc` will quote the code extract, the extra information that the warning brings should usually be more about the context (such as in which function this is occurring).
So I propose to improve further this PR by modifying those, but it would be most helpful to have an example program for each of those warnings, to make sure the message does help understanding the problem.
It also contains a couple of other things to fix (`TODO` and one message that seems dead code).

Cleanup QCheck-STM warnings

---

plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/hashtbl.mli
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml

Gospel now supports more standard constructs (partial applications, patterns for arguments in anonymous functions, etc.) so make use of them in tests

Use more idiomatic specifications

---

plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/test/test_errors.t

Unification of the SUT type is used in two different contexts:
- when handling a value, to know if its SUT-type argument has a compatible type with the one currently configured;
- when handling the declaration of the SUT type itself.
In the first case, we just want to skip the value with a warning; in the second case, we need to error out
Consequently:
- Add a new kind of error
- Feed `unify` with the information to know in which case we are
I’m a bit unsure about the phrasing of the error message, though.
Closes #133

Distinguish SUT-type unification errors

---

plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/test/all_warnings_errors.expected

This PR proposes a new warning message when the `next_state` case cannot be computed with the ensures clauses present in the specifications.
This is an attempt to answer point 4 in #150

Adapt warning message for ensures not found

---

plugins/qcheck-stm/src/ir.ml
plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected

- Handle tuple as returned value
- Remove duplicated code
- Support tuple where needed
Close #143

handle returned tuple

---

dune-project
ortac-core.opam
ortac-monolith.opam
ortac-qcheck-stm.opam
ortac-runtime-monolith.opam
ortac-runtime.opam
ortac-wrapper.opam
plugins/qcheck-stm/doc/dune
plugins/qcheck-stm/doc/example.mli
plugins/qcheck-stm/doc/example_for_all.mli
plugins/qcheck-stm/doc/example_ghost.mli
plugins/qcheck-stm/doc/example_ill_formed_quantification.mli
plugins/qcheck-stm/doc/example_incompatible_type.mli
plugins/qcheck-stm/doc/example_limitations.mli
plugins/qcheck-stm/doc/example_next_state.mli
plugins/qcheck-stm/doc/example_unknown_type.mli
plugins/qcheck-stm/doc/index.mld

This PR is based on #152 in order to have to latest warning messages.

Documentation/tutorial for ortac-stm plugin

---

plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref_stm_tests.expected.ml

Also drop the explicit `sequential`, so that users only have to change `STM_sequential` into `STM_domain` if they want to test their module in a parallel setting
This makes the display of `dune build @launchtests` a bit more useful.

Display the name of the tested module in the test run

---

plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/sequence_model.ml
plugins/qcheck-stm/test/sequence_model.mli
plugins/qcheck-stm/test/sequence_model_stm_tests.expected.ml
src/core/context.ml
src/core/context.mli
src/core/ocaml_of_gospel.ml
src/core/ocaml_of_gospel.mli

Add a `tystdlib` to the Context, similar to the `stdlib` but for types
Use `tystdlib` in `Ocaml_of_gospel` functions translating types
Adapt QCheck-STM to feed the context to those translation functions
Add a new test for QCheck-STM using the `sequence` type for the model
Closes #155

Translate types of the Gospelstdlib

---

plugins/qcheck-stm/doc/index.mld

Content part was empty and pointing to the different modules'
documentation is not really relevant.

Small documentation cleanup

---

CHANGES.md
plugins/qcheck-stm/doc/index.mld
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected

Fixes #171
This PR proposes to check for out of scope variables (returned values when building `next_state` function) in the `subst_term` function.
It can be argued that `subst_term` is now doing a lot of different things, but the added feature does not add lot of complexity, I used an optional arguement so that the change is transparent for user that does not need the new feature, and writing another function implementing this check would necessitate the same traversal of the term type.
Non compiling code is not generated anymore, but if the `next_state` function has not been generated, the user stay unaware of the why.
I didn't fix this last problem in this PR because it may necessitate a larger reflexion on which errors we want to display and which errors we want to forget about.

Check for out of scope variables.

---

dune-project

This will hopefully fix the failures from the lower-bounds checks.

Require a version of mdx supporting `.mld` files

---

ortac-qcheck-stm.opam

Missing update from #178, that should hopefully fix lower-bound failures

Update OPAM file

---

CHANGES.md
bin/registration.ml
bin/registration.mli
plugins/qcheck-stm/src/ortac_qcheck_stm.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli

This PR proposes to add a quiet flag to ortac. The flag is exposed as part of `Ortac_core.Registration` so it can be used by different plugins. Then the flag is used by `ortac-qcheck-stm`.
Using a flag implies that there are only too level of verbosity for warnings (errors are always displayed when they occur). We may to add more control over the verbosity in the future, but I think we should wait for more stability in the warning system. Still, I believe the user can benefit from a quiet mode, especially when generating tests with dune.
Related to #151

Add a quiet flag

---

CHANGES.md
plugins/qcheck-stm/src/ortac_qcheck_stm.ml
plugins/qcheck-stm/src/stm_of_ir.ml

This PR proposes to add an include option to the `qcheck-stm` cli. This will include the module passed as value of the option in the generated code. The idea is to allow the user to easily add `STM.ty` extensions and `STM.Utils.pp*`s without having to edit the generated file by hand.
This PR does not move the configuration in the included module (the `init_sut` expression and the `sut` type expression given by the user on the cli).

Add an include option to `qcheck-stm` cli

---

.ocamlformat-ignore
dune-project
examples/README.md
examples/dune
examples/varray_circular_spec.ml
examples/varray_circular_tests.ml
examples/varray_incl.ml
examples/varray_sig.ml
examples/varray_spec.ml
examples/varray_tests.ml
ortac-examples.opam

This PR add the [varray](https://github.com/art-w/varray) example.
It is bassed on the not yet merged #177, please consider only the two last commits.
There were four challenges, of different importance:
- The specifications are in an `ml` file and Gospel does not read `ml` file. The proposed solution/workaround is to extract the content of the module signature we are interested in.
- Writing specifications with Gospel `sequence` type is not that easy (it is very possible that review reveals some off-by-one mistakes!)
- User have to write some dune machinery in order to test different Functor instantiations.
- The included module is a bit bigger than the one for the #177 example and need to be included in two different tests. We had to make it a library. The size of the included module is …

Varray example

---

examples/dune

Editing the *_sig.ml files didn't cause the test to be rebuilt, unless a `dune clean && dune runtest --cache=disabled` was used.
`ortac` depends on the `mli` files (which are created by another rule from the `_sig.ml` files), this dependency can be turned into a hard failure by enabling sandboxing:
```
$ dune runtest --sandbox=hardlink --force
Entering directory '/var/home/edwin/git/ortac-qcheck-stm'
File "examples/dune", line 70, characters 0-368:
70 | (rule
71 |  (mode promote)
72 |  (alias runtest)
....
89 |      "char t"
90 |      --include=varray_incl
91 |      --quiet)))))
ortac: FILE argument: Error: `varray_spec.mli' not found
Usage: ortac qcheck-stm [OPTION]… FILE INIT SUT
Try 'ortac qcheck-stm --help' or 'ortac --help' for more information.
```
Add the missing dependencies and …

add missing dependencies for tests

---

dune-project
ortac-wrapper.opam

Other plugins doesn't declare it and documentation doesn't say it is necessary.

Remove dune-site dep for ortac-wrapper

---

.github/workflows/gh-pages.yml

setup-ocaml/deploy-doc was deprecated in favour of using upstream deployment actions

Rewrite the workflow to deploy the documentation

---

.github/workflows/gh-pages.yml

Follow-up to #191 which didn’t provide enough permissions for the deployment.

Grant the necessary permissions to deploy to github pages

---

ortac-wrapper.opam
ortac-wrapper.opam.template
plugins/wrapper/src/ir_of_gospel.ml

Gospel PR #374 modified how type invariants are stored in the typed ast.
This PR pin the new version (pin to be removed when a new version of Gospel is
released) and update Ortac/Wrapper code accordingly.

update to latest gospel

---

CHANGES.md
examples/lwt_dllist_tests.ml
examples/varray_circular_tests.ml
examples/varray_tests.ml
plugins/qcheck-stm/doc/index.mld
plugins/qcheck-stm/src/config.ml
plugins/qcheck-stm/src/ir.ml
plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/runtime/ortac_runtime_qcheck_stm.ml
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/all_warnings_errors.expected
plugins/qcheck-stm/test/array_errors.expected
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl_errors.expected
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/invariants_stm_tests.expected.ml
plugins/qcheck-stm/test/record_errors.expected
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref_errors.expected
plugins/qcheck-stm/test/ref_stm_tests.expected.ml
plugins/qcheck-stm/test/sequence_model_errors.expected
plugins/qcheck-stm/test/sequence_model_stm_tests.expected.ml

This PR is the continuation of, and is based on, #202.
Please consider only the six last commits.
This PR makes the failure message print a runnable scenario with information about returned and expected values.
It uses the same mechanism as introduced in #202 for communicating with `Qcheck.fail_reportf`.
For printing the commands with their `sut` argument in the right place, only the generated `show_cmd` has been modified.
Printing the user-provided value for `init_sut` is quite straightforward, we just have to pass the information to the runtime.
Printing the expected value is a bit more complicated.
First, we look at the Gospel specifications to see if there is enough information to compute the expected returned value (some functions may be specified in a way that their contract doesn't …

Print runnable scenario in case of test failure

---

plugins/dune-rules/test/test.t

This tiny PR fixes a bug with the `dune-rules` cram test which might trigger dynlink failures. It also proposes to rephrase a sentence and to fix typos.

Fix a small bug in a cram test and some typos

---

CHANGES.md
examples/lwt_dllist_tests.ml
examples/varray_circular_tests.ml
examples/varray_tests.ml
plugins/qcheck-stm/src/runtime/ortac_runtime_qcheck_stm.ml
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/invariants_stm_tests.expected.ml
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref_stm_tests.expected.ml

This PR proposes to add support for exceptional behaviour when printing a runnable scenariowhen a test is failing.
This PR is based on #204, please consider only the two last commits.
This PR should complete the story to fix #188
Again, if we introduce a bug in `plugins/qcheck-stm/test/array.ml` (here `let get a _ = get a 7`), we have now:
```
λ dune build @launchtests
File "plugins/qcheck-stm/test/dune.inc", line 49, characters 0-75:
49 | (rule
50 |  (alias launchtests)
51 |  (action
52 |   (run %{dep:array_stm_tests.exe} -v)))
random seed: 163835566
generated error fail pass / total     time test name
[✗]    1    0    1    0 / 1000     0.0s Array STM tests (generating)
--- Failure --------------------------------------------------------------------
Test Array STM tests failed (5 shrink …
```

Add support for exceptional behaviour to printing runnable scenario

---

dune-project
ortac-core.opam
ortac-dune.opam
ortac-examples.opam
ortac-monolith.opam
ortac-qcheck-stm.opam
ortac-runtime-monolith.opam
ortac-runtime-qcheck-stm.opam
ortac-wrapper.opam

4.12.0 is neccessary for `Either`

Bump all OCaml version to the same number

---

CHANGES.md
bin/cli.ml

Fixes #216
The inspiration comes from [this example](https://erratique.ch/software/cmdliner/doc/examples.html#exdarcs)
Though use of `ret` is [discouraged](https://erratique.ch/software/cmdliner/doc/Cmdliner/Term/index.html#val-ret).
But I didn't find any alteratives.

Move to use a default `Cmdliner.term` rather than the `usage` function

---

CHANGES.md
plugins/qcheck-stm/doc/example_empty_cmd.mli
plugins/qcheck-stm/doc/example_ghost.mli
plugins/qcheck-stm/doc/index.mld
plugins/qcheck-stm/src/reserr.ml
plugins/qcheck-stm/src/reserr.mli
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/dune
plugins/qcheck-stm/test/empty_cmd.mli
plugins/qcheck-stm/test/empty_cmd_config.ml
plugins/qcheck-stm/test/empty_cmd_errors.expected
plugins/qcheck-stm/test/test_errors.t

This PR adds a new error which is triggered when there are no commands produced during the translation from Gospel to OCaml. 
This fixes #213

Add empty cmd error

---

dune-project
ortac-examples.opam
ortac-qcheck-stm.opam
ortac-runtime-qcheck-stm.opam

There is a double objective here:
1. make `opam install ortac-qcheck-stm` put the user in a position where tests can be generated and run
2. fix lower bounds

Clean up some dependencies

---

CHANGES.md
examples/lwt_dllist_spec_tests.ml
examples/varray_circular_spec_tests.ml
examples/varray_spec_tests.ml
plugins/qcheck-stm/src/runtime/ortac_runtime_qcheck_stm.ml
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml
plugins/qcheck-stm/test/custom_config_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/invariants_stm_tests.expected.ml
plugins/qcheck-stm/test/queue_stm_tests.expected.ml
plugins/qcheck-stm/test/record_stm_tests.expected.ml
plugins/qcheck-stm/test/ref_stm_tests.expected.ml
plugins/qcheck-stm/test/sut_in_type_stm_tests.expected.ml
plugins/qcheck-stm/test/test_without_sut_stm_tests.expected.ml
plugins/qcheck-stm/test/tuples_stm_tests.expected.ml

Fixes #248
As suggested in the issue, the PR add a variant with three constructors to `Ortac_runtime_qcheck_stm` making it possible to pass the information whether the result is a value, a protected value or an exception from the generated tests to the runtime.
We don't really have tests for failing tests, which explains why we didn't spot the bug earlier. I'll open an issue for that, to keep this PR small and focused on the fix.

Fix display of the runnable scenario for protected values

---

plugins/qcheck-stm/README.md

IIUC, this limitation was lifted by #247 and #253

Remove left-over multiple-ts limitation from QCheck-STM README

---

plugins/qcheck-stm/test/all_warnings.mli
plugins/qcheck-stm/test/all_warnings_errors.expected
plugins/qcheck-stm/test/conjunctive_clauses.mli
plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl.mli
plugins/qcheck-stm/test/hashtbl_errors.expected
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml
plugins/qcheck-stm/test/sut_in_type.mli
plugins/qcheck-stm/test/sut_in_type_stm_tests.expected.ml
plugins/qcheck-stm/test/test_without_sut.mli
plugins/qcheck-stm/test/test_without_sut_stm_tests.expected.ml
plugins/qcheck-stm/test/tuples.mli
plugins/qcheck-stm/test/tuples_errors.expected
plugins/qcheck-stm/test/tuples_stm_tests.expected.ml

Fixes #278
This should also help #277.
I didn't change the tests for the wrapper mode as using sequences would mean supporting models (see #224)

Replace lists by sequences in Ortac/QCheck-STM tests

---

CHANGES.md
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/array.mli
plugins/qcheck-stm/test/array_stm_tests.expected.ml

Due to how `Gospel.Identifier.Ident.create` guarantee identifier uniqueness, some setup was generating `QCheck.Fn.apply_1` call in the generated code.
This PR fixes this behaviour by extracting the generation of this identifier so that it is done at most once per run.

Fix generation of the `QCheck.Fn.apply` identifier

---

CHANGES.md
examples/lwt_dllist_spec_tests.ml
examples/varray_circular_spec_tests.ml
plugins/qcheck-stm/src/ir_of_gospel.ml
plugins/qcheck-stm/test/array_errors.expected
plugins/qcheck-stm/test/array_stm_tests.expected.ml
plugins/qcheck-stm/test/hashtbl_errors.expected
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml

Dealing with coercions form boolean to prop, Gospel turns equalities between a boolean and a prop into a double implication.
For example, the postcondition in:
```ocaml
val mem : 'a -> 'a t -> bool
(*@ b = mem a t
ensures b = Sequence.mem t.contents a *)
```
Will be translated as `b = true <-> Sequence.mem t.contents a`.
This caused some warnings about incomplete computation of the expected returned value (as noted in #269) where the user was sure to have follow what say the documentation (and they was right).
This PR fixes this by exploring `Iff` cases (following the pattern above) in the search for candidates for the returned value description.
It also makes this search more flexible/complete by exploring the symmetric, both for equality and double implication.

Make search for returned value description more flexible

---

CHANGES.md
plugins/monolith/test/generated/wrapper.expected.ml
plugins/wrapper/src/failure.ml
plugins/wrapper/src/failure.mli
plugins/wrapper/src/ir_of_gospel.ml
plugins/wrapper/test/generated/wrapper.expected.ml

When a precondition or postcondition is violated, Ortac generates a raise to `Violated_invariant` from the `Ortac_runtime`, which is incorrect (as explained in [#294]). The expected behaviour is to raise `Violated_condition` instead, as preconditions and postconditions are contract conditions, not invariants.
This PR fixes this by matching `kind` with the expected error type when `kind` is violated.
```ocaml
let violated kind = match kind with
| `Pre | `Post -> violated_condition (term_kind kind)
| _ -> violated_invariant (term_kind kind)
```

Fix incorrect error type for violated preconditions and postconditions

---

CHANGES.md
plugins/qcheck-stm/src/stm_of_ir.ml
plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml

This PR fixes #298
The fix is simpler that what I first thought, which is good news.

[QCheck-STM] Fix labelled arguments in runnable scenario

---

CHANGES.md
plugins/wrapper/src/ir.ml
plugins/wrapper/src/ir_of_gospel.ml
plugins/wrapper/src/report.ml
plugins/wrapper/test/generated/dune
plugins/wrapper/test/generated/lib_model.ml
plugins/wrapper/test/generated/lib_model.mli
plugins/wrapper/test/generated/test.ml
plugins/wrapper/test/generated/wrapper_model.expected.ml

WIP:
This PR adds support for models in the Wrapper plugin, using ideas from #224.
To enable model support in Wrapper, a projection function should be implemented and exposed in the interface file. This function should be named the same as the gospel model it targets and annotated in the interface file with the attribute `[@@model]`.
When multiple models are defined, the same number of projection functions should be provided.
Internally, these projection functions are handled as regular `values` except that we register if it has the attribute `model` or not.
For example, the projection function `view`:
```ocaml
type 'a t
(*@ mutable model view : 'a sequence *)
val view : 'a t -> 'a list [@@model]
```
During translation, `collect_model` replaces all occurrences of the gospel model with …

Add support for models in the wrapper plugin

---

CHANGES.md
plugins/wrapper/src/report.ml
plugins/wrapper/test/generated/dune
plugins/wrapper/test/generated/test_error.t

This PR addresses issue #318 by emitting a warning in the error output when a model declared in Gospel does not have a corresponding projection function.
Since projection functions are required to support models in the wrapper generation, Ortac should skip code generation in such cases and inform the user through a warning message.

Prevent code generation if required model projection is absent

---

CHANGES.md
plugins/qcheck-stm/src/runtime/ortac_runtime_qcheck_stm_sequential.ml
plugins/qcheck-stm/src/runtime/report.ml
plugins/qcheck-stm/src/runtime/report.mli

This PR is in preparation of reusing some of the bug report functionalities in the domain runtime.
It is build upon previous PRs, please consider only the 8 last commits.

Refactor bug report printing

---

CHANGES.md
examples/dune
examples/dune.lwt_dllist.inc
examples/dune.treiber_stack.inc
examples/dune.varray_circular.inc
examples/treiber_stack_spec_tests.ml
plugins/dune-rules/src/dune_rules.ml
plugins/dune-rules/src/qcheck_stm.ml
plugins/dune-rules/src/qcheck_stm.mli
plugins/dune-rules/test/test.t
plugins/qcheck-stm/src/config.ml
plugins/qcheck-stm/src/ortac_qcheck_stm.ml
plugins/qcheck-stm/src/stm_of_ir.ml

This PR proposes to add a `--count` optional argument to the `ortac qcheck-stm` and the `ortac dune qcheck-stm` sub-commands.
The default value is set to 1000, which is the value that was hard-coded before.
There is one UX decision that could be argued against: in the absence of the `--count` argument in the `ortac dune qcheck-stm` sub-command, the default value is explicitly given to the `ortac qcheck-stm` sub-command in the generated dune rules.

[QCheck-STM+Dune] Add count optional argument
