ortac.opam, src/core/translation.ml, test/suite/arith/dune, test/suite/arrays/dune, test/suite/dune, test/suite/terms/dune, test/suite/test.ml, test/suite/types.ml, test/suite/types.mli, test/suite/types/dune, test/suite/types/lib.ml, test/suite/types/lib.mli
This adds record fields access support.
=> Upgrade to the latest gospel version

ortac-runtime-monolith.opam, src/core/warnings.ml, src/monolith/generators.ml, src/monolith/ortac_monolith.ml, src/monolith/printers.ml, src/monolith/runtime/dune, src/monolith/runtime/ortac_runtime_monolith.ml, src/monolith/runtime/ortac_runtime_monolith.mli, src/monolith/warnings.ml
In this PR, I add support for variants in the frontend for Monolith.
=> Monolith variants

ortac.opam, src/core/translate.ml, src/core/translation.ml
We have to wait until the CI sees the new Gospel release.
=> Upgrade to gospel.0.1.0

.ocamlformat-ignore, ortac-runtime-monolith.opam, ortac-runtime.opam, ortac.opam, test/generated/default/dune, test/generated/default/errors.expected, test/generated/default/wrapper.expected.ml, test/generated/dune, test/generated/dune.common, test/generated/lib.ml, test/generated/lib.mli, test/generated/monolith/dune, test/generated/monolith/errors.expected, test/generated/monolith/wrapper.expected.ml
Add some diff tests on generated files and warnings so that we will be informed if we break something in a frontend.
=> add some diff tests on generated files

.ocamlformat, src/core/generate.ml, src/core/translated.ml, src/core/translation.ml, test/suite/exceptions.ml, test/suite/exceptions/lib.ml, test/suite/exceptions/lib.mli
Fixes #65 and #64.
Thanks @naomiiiiiiiii for reporting these, and sorry for the late fix.
=> Better `checks` handling

ortac.opam, src/core/drv.ml
=> Rename seq into sequence (after gospel#254)

test/suite/test.ml
=> Update project name in test suite

plugins/qcheck-stm/src/ir.ml, plugins/qcheck-stm/src/ir_of_gospel.ml, plugins/qcheck-stm/src/reserr.ml, plugins/qcheck-stm/src/reserr.mli, plugins/qcheck-stm/src/stm_of_ir.ml, plugins/qcheck-stm/test/hashtbl_errors.expected, plugins/qcheck-stm/test/hashtbl_stm_tests.expected.ml, src/core/ocaml_of_gospel.ml
- Add promote_opt to Reserr
- Fix pattern translation in core
- Add a ghost_function field to ir
- Store the implemented ghost functions in ir
- Translate and integrate to generated module the ghost functions
- Update tests
=> Add support for ghost functions and predicates

ortac-monolith.opam, ortac.opam, plugins/monolith/test/generated/wrapper.expected.ml, src/default/ir_of_gospel.ml, test/generated/wrapper.expected.ml
Location has been fixed so display in error reporting is better
=> update to the latest gospel

bin/dune, dune-project, ortac-core.opam, ortac-monolith.opam, ortac-qcheck-stm.opam, ortac-runtime-monolith.opam, ortac-wrapper.opam, plugins/monolith/src/dune, plugins/monolith/src/runtime/dune, plugins/monolith/test/generated/dune, plugins/qcheck-stm/src/dune, plugins/wrapper/src/dune, plugins/wrapper/test/suite/dune, src/core/dune, test/runtime/dune
This is an attempt to make the experimental `opam-dune-lint` CI feature happy.
=> Clean up opam and dune files

plugins/qcheck-stm/src/config.ml, plugins/qcheck-stm/test/record.ml, plugins/qcheck-stm/test/record.mli, plugins/qcheck-stm/test/record_errors.expected, plugins/qcheck-stm/test/record_stm_tests.expected.ml
Add pure OCaml and ghost functions to the context
Add simple tests for the feature
=> Add pure OCaml and ghost functions to the context

plugins/qcheck-stm/src/ir_of_gospel.ml, plugins/qcheck-stm/test/conjunctive_clauses.mli, plugins/qcheck-stm/test/conjunctive_clauses_stm_tests.expected.ml, plugins/qcheck-stm/test/dune
=> Explore conjunctive clauses

README.md
=> Update the README with the released packages

CHANGES.md, plugins/qcheck-stm/src/stm_of_ir.ml, plugins/qcheck-stm/test/sequence_model.ml, plugins/qcheck-stm/test/sequence_model.mli, plugins/qcheck-stm/test/sequence_model_stm_tests.expected.ml, src/core/builder.ml, src/core/builder.mli, src/core/ocaml_of_gospel.ml
=> Add a guard testing equality for integer constant pattern

.github/workflows/changelog.yml
Just a reminder to complete the CHANGES.md file.
Shamelessly stolen from gospel repository.
=> Add a CI workflow for changelog

.github/workflows/gh-pages.yml
Hopefully, copying the documentation of the deploy action should get us closer to something working?
=> github pages deployment, take 3

plugins/qcheck-stm/src/config.ml
=> Use existing functionaly from `Ppxlib.Longident`

ortac-runtime.opam
This version brings the last breaking change in Monolith.
=> Add minimal version for Monolith

examples/varray_circular_spec_config.ml, examples/varray_circular_spec_tests.ml, examples/varray_spec_config.ml, examples/varray_spec_tests.ml, plugins/qcheck-stm/doc/index.mld
Fixes #255 and #257 (hopefully)
=> Update Ortac/QCheck-STM documentation

src/core/warnings.ml
Spotted while hacking on function generation support #270 
It triggered my ocd and hence require prompt fixing! :sweat_smile:
=> Fix Unkown_kind

CHANGES.md, plugins/monolith/test/generated/wrapper.expected.ml, plugins/wrapper/test/generated/dune, plugins/wrapper/test/generated/lib.ml, plugins/wrapper/test/generated/lib.mli, plugins/wrapper/test/generated/test.ml, plugins/wrapper/test/generated/wrapper.expected.ml
Testing cases where the generated instrumented OCaml program should fail.
=> Add tests to wrapper plugin

CHANGES.md, plugins/wrapper/src/ir_of_gospel.ml, plugins/wrapper/test/generated/lib_model.ml, plugins/wrapper/test/generated/lib_model.mli, plugins/wrapper/test/generated/wrapper_model.expected.ml
This PR completes the support for models in preconditions, a feature that was missing in PR #305.
=> Fix missing model support in preconditions

LICENSE, dune-project, ortac-dune.opam, ortac-wrapper.opam
=> Add Charlène Gros as new author
